---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - bash-completion
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - sqlite
  - mcrypt
  - node
  - nvm
  - php
  - ssh-copy-id
  - openssl
  - wget
  - zsh-history-substring-search
  - fish
  - dotnet
  - git
  - pyenv
  - speedtest-cli
  - rust
  - r
  - ruby

homebrew_taps:
  - homebrew/core
  - homebrew/cask

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
