---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - git
  - github/gh/gh
  - gpg
  - httpie
  - sqlite
  - node
  - nvm
  - php
  - ssh-copy-id
  - openssl
  - wget
  - fish
  - git
  - coreutils
  - pyenv
  - tmux
  - bash
  - zsh
  # - go
  # - ansible # Installed via Pip.
  # - rust
  # - r
  # - ruby
  # - bash-completion
  # - dotnet
  # - speedtest-cli

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - visual-studio-code
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - slack
  - discord
  - zoom
  - zotero
  - kitty
  - thingsmacsandboxhelper
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
